# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='id_unidade_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_unidades_medida', to='unidades_medida.UnidadeMedida'),
        ),
    ]
